### ISSUE TITLE
Make a Makefile 

### ISSUE THREAD

**Issue by clee231** [pawbyte/Game-Pencil-Engine#1]
In order to make building the engine easier for users, a Makefile should be used to aid in the automated build process. 

This will mostly affect Linux users, but other platforms could potentially utilize the Makefile as well to reduce the dependency on Code::Blocks. At this point, we're only looking for a Makefile for Linux. (I'm not sure if it's even possible to use a Makefile on Windows easily.)

**Comment by Vaelatern** [comment]
I took a stab at this.

Whats the name of the target binary?

**Comment by Vaelatern** [comment]
Ah, found it. Giving this a go.

**Comment by Vaelatern** [comment]
Mve to close due to merge.
