### ISSUE TITLE
Hello World Tutorial

### ISSUE THREAD

**Issue by theweirdn8** [pawbyte/Game-Pencil-Engine#12]
I have created a Hello World tutorial on create.pawbyte.com . 

It is effectively a first draft and has a combination of screenshots, text and code. Please check it out and review any grammatical or formatting issues. Gracias.

http://gamepencil.pawbyte.com/2017/10/26/hello-world-tutorial/

**Comment by clee231** [comment]
I've made my initial edits and have published my revisions. Hopefully they make sense.

**Comment by theweirdn8** [comment]
Okay I made a few small changes to the "Start Page" image and also the 1st paragraph. I was told it was too preachy on IRC.

**Comment by theweirdn8** [comment]
Okay, will also include in new releases of GPE too.
