### ISSUE TITLE
Windows Defender quarantines the executable for 1.2.1

### ISSUE THREAD

**Issue by AsixJin** [pawbyte/Game-Pencil-Engine#20]
I downloaded Game Pencil 1.2.1 for my Windows 10 machine and Windows Defender detected as some kind of malware. I've linked below what Defender said and this does not happen with the previous version (1.1.3)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Azden.B!cl

**Comment by clee231** [comment]
Ran a virus scan on the main 1.2.1 Windows Executable.  1 out of 67 virus scanners reported malicious activity. (Cylance) (https://www.virustotal.com/#/file/9e2402353d205936590046404b80fbcd0916d38bec8a9d1adb70acb83ddcaccf/detection)

As far as I know, we haven't been compromised at all, so the file should be clean.
Further investigation is needed.

**Comment by clee231** [comment]
Testing on **Windows 10 Pro** Version **1709** Build **16299.248**.
Using Window Defender Security Center, Threat Definition version: **1.261.1676.0**

Using `GPE_Windows_v1_2_1_RC.zip` from GitHub releases yield: **0** threats, **1,371** files scanned.

Hmm... Can't seem to recreate the issue. Can anyone else confirm?

**Comment by clee231** [comment]
@AsixJin - Can you provide us with the **Threat Definition version** that you are using?
Here are instructions on how to find this: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus#definition-version

**Comment by AsixJin** [comment]
I'll get to it the moment I get back to my computer and I'll do the same on my other machine.
