### ISSUE TITLE
GPE_SpecialMenu_Branch::save_branch_data is defined as returning bool, empty function

### ISSUE THREAD

**Issue by Heceldi** [pawbyte/Game-Pencil-Engine#26]
in paw_gui_stree.cpp

bool GPE_SpecialMenu_Branch::save_branch_data(std::ofstream * fileTarget, int nestedFoldersIn  )
{

}

no return, or function

**Comment by Heceldi** [comment]
just found a second copy of this function...

bool GPE_SpecialMenu_Tree::save_branch_data(std::ofstream * fileTarget, int nestedFoldersIn  )
{
    if( fileTarget!=NULL && fileTarget->is_open() )
    {
        GPE_SpecialMenu_Branch * cBranch = NULL;
        for( int i = 0; i < (int)subElements.size(); i++)
        {
            cBranch = subElements[i];
            if( cBranch!=NULL )
            {
                cBranch->save_branch_data( fileTarget, 0 );
            }
        }
    }
    return false;
}

**Comment by theweirdn8** [comment]
Corrected, will update soon.
