### ISSUE TITLE
Can we plan to support Python too?

### ISSUE THREAD

**Issue by sp-mishra** [pawbyte/Game-Pencil-Engine#33]
I came across this **awesome** game engine while I was looking for a simple game engine to start working on as a hobby. (For some time I have the craving to start with gaming :) )
Can we investigate and add support for Python language? This will help us leverage Machine learning capabilities also if needed.
Just a thought.

**Comment by theweirdn8** [comment]
Due to the sheer work that can not be added by me or Chase, but maybe a contributor can add that.
