### ISSUE TITLE
compiling with meson - src/AOSGUI does not exist

### ISSUE THREAD

**Issue by luckythandel** [pawbyte/Game-Pencil-Engine#38]
I tried to compile it on my system but this happened. 
Screenshot -->  https://imgur.com/lhaFNLF.png

**Comment by theweirdn8** [comment]
Good morning,

Sorry this version was meant to be a code dump and wasn't production ready. I will be uploading new working tree soon. Life has been busy. I just became a dad last week. 

If you could hold tight one more week I feel it would be worth it

**Comment by luckythandel** [comment]
Congratulations dude🎉🎉🎉🎉🎉🎉🎉🎉
Take time as much as you want. You seems a nice person.
By the way, is it a girl or boy?

**Comment by theweirdn8** [comment]
He's a handsome young boy. Also feel free to join our discord server https://discordapp.com/invite/bua3rDW
