### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by riidom** [pawbyte/Game-Pencil-Engine#44]
Hi there,
found that project while browsing on itch.io, both domains pawbyte.com and gamepencil.net seem to be unreachable (the latter is the current one, I assume?)
I wondered, is the project on hold, or still active?

**Comment by clee231** [comment]
> Hi there,
> found that project while browsing on itch.io, both domains pawbyte.com and gamepencil.net seem to be unreachable (the latter is the current one, I assume?)
> I wondered, is the project on hold, or still active?

Hi @riidom,

Thanks for the issue report! We're still slowly developing the engine as we sort out life happenings.

The server has been experiencing a lot of downtime as of late, but we haven't had too much time to dedicate to look into why...
We'll probably end up moving the site elsewhere over the next few months or so. I rebooted the server just now and it seems to be working for now.

Things like our documentation site should be more reliable though. That's hosted elsewhere. (https://docs.gamepencil.net)

**Comment by riidom** [comment]
Ah, I didn't try reaching the docs directly, thanks for the heads up!
